package app.indusara.server.validator;

public enum ValidationResult {
    SUCCESS, INVALID_DISPLAY_NAME, INVALID_EMAIL, INVALID_FULL_NAME, INVALID_GENDER, INVALID_PASSWORD, INVALID_DOB, INVALID_CLUB_NAME, INVALID_JUDO_GRADE, INVALID_WEIGHT_CLASS, INVALID_PROVINCE, NO_PAYMENT
}
