version: '3'
services:
  mysql:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=iuklis123
      - MYSQL_DATABASE=judo-ranking
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80' 
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - DDL_MODE=create
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_NAME=judo-ranking
      - DB_PASSWORD=iuklis123
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0
